export const ORDER_STATE = {
    PROCESSING: "PROCESSING",
    PLACED: "PLACED",
    CONFIRMED: "CONFIRMED",
    OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
    DELIVERED: "DELIVERED",
    CANCELLED: "CANCELLED",
}

export const ORDER_STATE_COLOR = {
    PROCESSING: "#f0ad4e",
    PLACED: "#0275d8",
    CONFIRMED: "#5bc0de",
    OUT_FOR_DELIVERY: "#6194eb",
    DELIVERED: "#5cb85c",
    CANCELLED: "#d9534f",
}